# Permalinks
permalink:           /:year/:title/

# Setup
title:               Вторая система
tagline:             'Блог о рациональном мышлении'
description:         'Блог, где я рассказываю обо всём, что связано с попытками мыслить более рационально.'
url:                 https://rationalblog.github.io/
baseurl:             'https://rationalblog.github.io'
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

# About/contact
author:
  name:              Автор
  url:               http://rationalblog.github.io
  email:             myrationalblog@gmail.com

# Custom vars


